Repository tokens-studio/figma-plugin, pull requests merged in 2024-07, with the labels that each got.

#2966 2962 unable to duplicate a token with the same name inside a set
  packages/tokens-studio-for-figma/src/app/components/EditTokenForm.tsx
  packages/tokens-studio-for-figma/src/i18n/lang/en/errors.json
  packages/tokens-studio-for-figma/src/i18n/lang/es/errors.json
  packages/tokens-studio-for-figma/src/i18n/lang/fr/errors.json
  packages/tokens-studio-for-figma/src/i18n/lang/hi/errors.json
  packages/tokens-studio-for-figma/src/i18n/lang/nl/errors.json
  packages/tokens-studio-for-figma/src/i18n/lang/zh/errors.json
Labels: 2.0-rc10

#2988 fix local variable references normalization
  packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/__tests__/getThemeReferences.test.ts
  packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/getThemeReferences.ts
Labels: 2.0-rc10

#2994 chore: remove style setting on node warning
  packages/tokens-studio-for-figma/src/utils/tryApplyVariableId.test.ts
  packages/tokens-studio-for-figma/src/utils/tryApplyVariableId.ts
Labels: QOL, 2.0-rc10

#3008 fix: maintain set ordering on creation
  packages/tokens-studio-for-figma/src/utils/tokenset/__tests__/findParentIndexToInsertSet.test.ts
  packages/tokens-studio-for-figma/src/utils/tokenset/__tests__/updateTokenSetsInState.test.ts
  packages/tokens-studio-for-figma/src/utils/tokenset/findParentIndexToInsertSet.ts
  packages/tokens-studio-for-figma/src/utils/tokenset/updateTokenSetsInState.ts
Labels: QOL, 2.0-rc10

#3022 fix: prevents duplicated format sensitive keys on tokens when pushing to remotes
  packages/tokens-studio-for-figma/src/app/components/createTokenObj.test.tsx
  packages/tokens-studio-for-figma/src/utils/convertTokensToObject.test.ts
  packages/tokens-studio-for-figma/src/utils/convertTokensToObject.ts
  packages/tokens-studio-for-figma/src/utils/setTokenKey.test.ts
  packages/tokens-studio-for-figma/src/utils/setTokenKey.ts
Labels: bug, bug_fix, 2.0-rc10

#3033 fix: push dialog toggles correctly
  packages/tokens-studio-for-figma/src/app/components/FormatSelector.tsx
  packages/tokens-studio-for-figma/src/app/components/PushDialog.tsx
  packages/tokens-studio-for-figma/src/app/components/modals/ExportModal.tsx
  packages/tokens-studio-for-figma/src/app/components/modals/PresetModal.tsx
Labels: bug, quick wins, QOL, plugin v2

#3032 Fix composition tokens not applying raw values for colours
  packages/tokens-studio-for-figma/src/plugin/setColorValuesOnTarget.ts
Labels: bug, plugin v2

#3035 fix: ensure remote changes are correctly tracked in the plugin
  packages/tokens-studio-for-figma/src/app/components/AppContainer/startupProcessSteps/__tests__/pullTokensFactory.test.ts
  packages/tokens-studio-for-figma/src/app/components/AppContainer/startupProcessSteps/pullTokensFactory.ts
  packages/tokens-studio-for-figma/src/app/components/BranchSelector.tsx
  packages/tokens-studio-for-figma/src/app/components/Footer.tsx
  packages/tokens-studio-for-figma/src/app/components/ImportedTokensDialog.test.tsx
  packages/tokens-studio-for-figma/src/app/components/modals/CreateBranchModal.tsx
  packages/tokens-studio-for-figma/src/app/store/providers/ado/ado.tsx
  packages/tokens-studio-for-figma/src/app/store/providers/bitbucket/bitbucket.tsx
  packages/tokens-studio-for-figma/src/app/store/providers/generic/versionedStorage.ts
  packages/tokens-studio-for-figma/src/app/store/providers/github/github.tsx
  packages/tokens-studio-for-figma/src/app/store/providers/gitlab/gitlab.tsx
  packages/tokens-studio-for-figma/src/app/store/providers/jsonbin.tsx
  packages/tokens-studio-for-figma/src/app/store/providers/supernova/supernova.tsx
  packages/tokens-studio-for-figma/src/app/store/providers/tokens-studio/tokensStudio.tsx
  packages/tokens-studio-for-figma/src/app/store/providers/url.tsx
  packages/tokens-studio-for-figma/src/app/store/remoteTokens.test.ts
  packages/tokens-studio-for-figma/src/app/store/remoteTokens.tsx
Labels: bug, plugin v2
